/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AddLyricDto } from './models/AddLyricDto';
export type { AddPlaylistMusicDto } from './models/AddPlaylistMusicDto';
export type { AlbumListVo } from './models/AlbumListVo';
export type { AlbumVo } from './models/AlbumVo';
export type { ArtistVo } from './models/ArtistVo';
export type { CreateRootAccountDto } from './models/CreateRootAccountDto';
export type { IsExistsRootAccountVo } from './models/IsExistsRootAccountVo';
export type { LoginDto } from './models/LoginDto';
export type { LyricFetchLog } from './models/LyricFetchLog';
export type { LyricFetchVo } from './models/LyricFetchVo';
export type { LyricVo } from './models/LyricVo';
export type { Music } from './models/Music';
export type { MusicDto } from './models/MusicDto';
export type { MusicResourceVo } from './models/MusicResourceVo';
export type { MusicVo } from './models/MusicVo';
export type { OrderItem } from './models/OrderItem';
export type { PageLyricFetchLog } from './models/PageLyricFetchLog';
export type { PlayHistoryVo } from './models/PlayHistoryVo';
export type { Playlist } from './models/Playlist';
export type { PlaylistVo } from './models/PlaylistVo';
export type { RemovePlaylistMusicDto } from './models/RemovePlaylistMusicDto';
export type { Response } from './models/Response';
export type { ResponseAlbumListVo } from './models/ResponseAlbumListVo';
export type { ResponseAlbumVo } from './models/ResponseAlbumVo';
export type { ResponseArtistVo } from './models/ResponseArtistVo';
export type { ResponseInteger } from './models/ResponseInteger';
export type { ResponseIsExistsRootAccountVo } from './models/ResponseIsExistsRootAccountVo';
export type { ResponseListAlbumVo } from './models/ResponseListAlbumVo';
export type { ResponseListArtistVo } from './models/ResponseListArtistVo';
export type { ResponseListLyricVo } from './models/ResponseListLyricVo';
export type { ResponseListMusic } from './models/ResponseListMusic';
export type { ResponseListMusicVo } from './models/ResponseListMusicVo';
export type { ResponseListPlayHistoryVo } from './models/ResponseListPlayHistoryVo';
export type { ResponseListPlaylistVo } from './models/ResponseListPlaylistVo';
export type { ResponseLyricFetchVo } from './models/ResponseLyricFetchVo';
export type { ResponseLyricVo } from './models/ResponseLyricVo';
export type { ResponseMusic } from './models/ResponseMusic';
export type { ResponseMusicVo } from './models/ResponseMusicVo';
export type { ResponseObject } from './models/ResponseObject';
export type { ResponsePageLyricFetchLog } from './models/ResponsePageLyricFetchLog';
export type { ResponsePlaylist } from './models/ResponsePlaylist';
export type { ResponsePlaylistVo } from './models/ResponsePlaylistVo';
export type { ResponseString } from './models/ResponseString';
export type { ResponseUserDetailVo } from './models/ResponseUserDetailVo';
export type { UpdateAlbumInfoDto } from './models/UpdateAlbumInfoDto';
export type { UpdateLyricDto } from './models/UpdateLyricDto';
export type { UpdatePlaylistInfoDto } from './models/UpdatePlaylistInfoDto';
export type { UpdateUserInfoDto } from './models/UpdateUserInfoDto';
export type { UserBasicVo } from './models/UserBasicVo';
export type { UserDetailVo } from './models/UserDetailVo';

export { AlbumControllerService } from './services/AlbumControllerService';
export { ArtistControllerService } from './services/ArtistControllerService';
export { AuthControllerService } from './services/AuthControllerService';
export { LyricControllerService } from './services/LyricControllerService';
export { MinIoControllerService } from './services/MinIoControllerService';
export { MusicControllerService } from './services/MusicControllerService';
export { PlayHistoryControllerService } from './services/PlayHistoryControllerService';
export { PlaylistControllerService } from './services/PlaylistControllerService';
export { SearchControllerService } from './services/SearchControllerService';
export { UserControllerService } from './services/UserControllerService';
